name: <FTName>
description: <FTName>
version: 1.0.1

publish_to: none

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  built_collection: ^5.0.0
  built_value: ^8.0.2
  provider: ^5.0.0-dev.0
  rxdart: ^0.26.0-nullsafety.0

  built_redux:
    git:
      url: https://github.com/ligastavok/built_redux.git
      ref: v8.x
  dioc:
    git:
      url: https://github.com/ligastavok/flutter_packages.git
      path: dioc/dioc
      ref: v1.x

  app_domain:
    path: ../app_domain
  # models:
  #   path: ../models
  neo_network:
    path: ../neo_network
  neo_storage:
    path: ../neo_storage
  icons_basic:
    path: ../features/icons/icons_basic

dev_dependencies:
  build_runner: ^1.10.2
  built_value_generator: ^8.0.2

  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

  dioc_generator:
    git:
      url: https://github.com/ligastavok/flutter_packages.git
      path: dioc/dioc_generator
      ref: v1.x

dependency_overrides:
  analyzer: ^1.2.0
  convert: ^3.0.0
  logging: ^1.0.0
  protobuf: ^2.0.0
  crypto: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/theme/

  fonts:
    - family: SFProDisplayRegular
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
    - family: SFProDisplayBold
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Bold.otf

flutter_intl:
  enabled: true
  class_name: <FTName | pascalcase>Intl
  main_locale: ru
  output_dir: lib/src/generated 
  arb_dir: lib/src/l10n