name: <FTName>
description: <FTName>
version: 1.0.1

publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  built_value: ^7.1.0
  built_collection: 4.3.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # hive: ^1.6.0-nullsafety.2 #1.4.4+1

  provider: ^5.0.0-nullsafety.5
  rxdart: ^0.26.0-nullsafety.1

  app_domain:
    path: ../app_domain
  neo_network:
    path: ../neo_network
  neo_error_converter:
    path: ../neo_error_converter

  icons_basic:
    path: ../features/icons/icons_basic

  # neo_storage:
  #   path: ../neo_storage

dev_dependencies:
  build_runner: ^1.10.2
  build_test: ^0.10.11
  built_value_generator: ^7.1.0
  pedantic: 1.10.0-nullsafety.3
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  file: 6.0.0-nullsafety.4
  process: 4.0.0-nullsafety.4
  platform: 3.0.0-nullsafety.4
  built_redux:
    git:
      url: https://github.com/ligastavok/built_redux
  dioc_generator:
    git:
      url: https://github.com/ligastavok/flutter_packages
      path: dioc/dioc_generator

dependency_overrides:
  analyzer: 0.40.6
  path_provider: ^1.4.0
  crypto: ^2.0.0
  async: 2.5.0-nullsafety.1
  built_value: ^7.1.0
  built_collection: 4.3.2
  intl: 0.17.0-nullsafety.2
  provider: ^5.0.0-nullsafety.5
  collection: ^1.15.0
  file: ^6.1.0
  meta: ^1.3.0
  path: ^1.8.0
  process: ^4.1.0
  platform: ^3.0.0
  built_redux:
    git:
      url: https://github.com/ligastavok/built_redux
  screenshots: ^2.1.1
  rxdart: ^0.26.0-nullsafety.1
  json_annotation: 4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/theme/

  fonts:
    - family: SFProDisplayRegular
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
    - family: SFProDisplayBold
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Bold.otf

flutter_intl:
  enabled: true
  class_name: <FTName | pascalcase>Intl
  main_locale: ru
  output_dir: lib/src/generated 
  arb_dir: lib/src/l10n