name: <FTName>
description: <FTName>
version: 0.0.1

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # pub.dev
  flutter_bloc: ^7.0.0
  built_collection: ^5.0.0
  built_value: ^8.0.2
  get_it: ^7.1.3
  provider: ^5.0.0
  rxdart: ^0.27.0
  visibility_detector: ^0.2.0
  flutter_sticky_header: ^0.6.0
  freezed_annotation: ^0.14.2

  #
  built_redux:
    git:
      url: https://github.com/ligastavok/built_redux.git
      ref: v9.x

  #
  actions:
    path: ../actions
  states:
    path: ../states
  app_domain:
    path: ../app_domain
  components:
    path: ../components
  models:
    path: ../models
  # neo_network:
  #   path: ../neo_network
  # neo_storage:
  #   path: ../neo_storage

dev_dependencies:
  freezed: ^0.14.2
  build: ^2.0.0
  build_runner: ^2.0.4
  built_value_generator: ^8.0.6

  cool_linter: ^1.0.3
  dart_code_metrics: ^3.3.0
  analyzer: 1.7.0

dependency_overrides:
  analyzer: 1.7.0
  args: ^2.0.0
  crypto: ^3.0.0
  meta: ^1.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/theme/

  fonts:
    - family: SFProDisplayRegular
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
    - family: SFProDisplayBold
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Bold.otf

flutter_intl:
  enabled: true
  class_name: <FTName | pascalcase>Localizations
  main_locale: ru
  output_dir: lib/src/generated 
  arb_dir: lib/src/l10n